server:
  port: 9091
logging:
  level:
    root: info
    com.zh.am: debug
spring:
  profiles:
    active: dev
  application:
    # spring cloud gateway中,不支持下划线的形式  see https://github.com/spring-projects/spring-framework/issues/24439
    name: access-management
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
# 用于jwt签名中的key
security:
  oauth2:
    resource:
      jwt:
        key-value: e868af84623e7d8a969c155059db797d
# open feign相关配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        errorDecoder: com.zh.am.config.FeignErrorDecoder
        decode404: true
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 120000