spring:
  application:
    name: gateway
  server:
    port: 9000
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能
      routes:
        - id: access-management
          uri: lb://access-management
          predicates:
            - Path=/am/api/**
          filters:
            - StripPrefix=1
  mvc:
    dispatch-options-request: true
#打开actuator所有监控点
management:
  endpoints:
    web:
      exposure:
        include: '*'
#jwt
security:
  oauth2:
    resource:
      jwt:
        key-value: e868af84623e7d8a969c155059db797d
        expire-minutes: 30
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    root: info
    com.zh.gateway: debug