spring:
  application:
    name: spring-cloud-eureka
server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    # eureka client刷新本地缓存时间 默认30s
    registry-fetch-interval-seconds: 3
  server:
    # eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
    # 默认30s,调整为3s
    response-cache-update-interval-ms: 3000
    # 启用主动失效，并且每次主动失效检测间隔为2s
    eviction-interval-timer-in-ms: 2000
    # dev环境 关闭自我保护机制
    enable-self-preservation: false
  instance:
    # 默认90s. 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除.
    # 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    lease-expiration-duration-in-seconds: 9
    # 默认30s. 服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 3
