server:
  port: 9088
spring:
  datasource:
    url: jdbc:mysql://rm-2zefmq87x5r426x16uo.mysql.rds.aliyuncs.com:3306/file_storage?useSSL=false&characterEncoding=UTF-8
    username: file_storage
    password: file_storage
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      test-while-idle: true
      test-on-borrow: true
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 55000
      validation-interval: 34000
      validation-query: SELECT 1
eureka:
  client:
    service-url:
      defaultZone: http://118.178.254.170:8000/eureka/
    registry-fetch-interval-seconds: 3
  instance:
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
management:
  endpoints:
    web:
      exposure:
        include: '*'
